### ISSUE TITLE
Refactor action bar

### ISSUE THREAD

**Issue by dmfs** [schedjoules/android-event-discovery-sdk#138]
In order to experience a better customer journey, as a user I want the actions to be located underneath the event description.
---
The separate address field should be removed and the address should be added as the label to the "directions" action.

**Comment by lemonboston** [comment]
So this is how it looks like currently:

![device-2017-03-22-140032](https://cloud.githubusercontent.com/assets/1077972/24198887/f5fb0852-0f07-11e7-837b-2e7c23cb3ee0.png)

@dmfs Regarding the locations, so do I get it correctly that the former `<location.name>, <address.street>, <address.locality>, <address.country>` should split to `<location.name>` as venue name for the location pin icon, as already in the screenshot above,
and `<address.street>, <address.locality>, <address.country>` should be the label of the current Direction action, right? But keep it as an Action, so that it has the link to open the map sent by the API.

**Comment by dmfs** [comment]
Yes that sounds correct. What's important is that Add-to-calendar and share now always have the same order. We're not using the order of the results anymore.

**Comment by lemonboston** [comment]
You mean that client takes over the definition of display ordering of the actions from the API? If yes, can we do that in a small separate story? To define the ranking of the 10 currently supported Actions and implement it in a nice way.

**Comment by dmfs** [comment]
This is not about ranking the elements. It's about not having them dynamically positioned anymore. With the new layout each action will have it's own specific place.

**Comment by lemonboston** [comment]
Yes, I remember that we are going to define fix places for elements, so user knows where to expect it.
But with how currently we handle these as Actions Links coming from API, in practice, we need to define an order now to guarantee their relative places.
So I've added rankings to them to be in this order, @dmfs , @wilfredstegeman let me know if you would like to reshuffle any:

...(datetime, venue, description)
book (will be the ticket button)
add-to-calendar
share
directions
info
call
buy
remind
watch
invite

**Comment by dmfs** [comment]
Sorry, where/why exactly do we need this ranking? I don't see any need to rank the actions.
