### ISSUE TITLE
Localized strings

### ISSUE THREAD

**Issue by wilfredstegeman** [schedjoules/android-event-discovery-sdk#150]
**English** 
```
<string name="schedjoules_location_picker_current_location">Current location</string>
   <string name="schedjoules_location_picker_current_location_locating">Find location…</string>
   <string name="schedjoules_location_picker_current_location_permission_rationale">To use your current location, please allow access to your location.</string>
   <string name="schedjoules_location_picker_current_location_permission_inform_about_phone_settings">To later enable current location display, allow access to your location from your device settings.</string>
   <string name="schedjoules_location_picker_current_location_error">We could not determine your location. Please tap to retry.</string>
   <string name="schedjoules_location_picker_caption_place_suggestions">Suggestions</string>
   <string name="schedjoules_location_picker_caption_recent_locations">Recent locations</string>
```

**Dutch**
```
<string name="schedjoules_location_picker_current_location">Huidige locatie</string>
   <string name="schedjoules_location_picker_current_location_locating">Locatie zoeken…</string>
   <string name="schedjoules_location_picker_current_location_permission_rationale">Om uw huidige locatie te kunnen gebruiken, geeft u toegang tot uw locatie.</string>
   <string name="schedjoules_location_picker_current_location_permission_inform_about_phone_settings">Om weergave van uw huidige locatie later mogelijk te maken, geeft u toegang tot uw locatie in de instellingen van uw toestel.</string>
   <string name="schedjoules_location_picker_current_location_error">Het is niet gelukt om uw locatie te bepalen. Klik om het opnieuw te proberen.</string>
   <string name="schedjoules_location_picker_caption_place_suggestions">Suggesties</string>
   <string name="schedjoules_location_picker_caption_recent_locations">Recente locaties</string>
```

**Comment by dmfs** [comment]
German
```
<string name="schedjoules_location_picker_current_location">Mein Standort</string>
   <string name="schedjoules_location_picker_current_location_locating">Standort wird ermittelt…</string>
   <string name="schedjoules_location_picker_current_location_permission_rationale">Bitte erlaube den Zugriff auf deinen Standort um diese Funkionen nutzen zu können.</string>
   <string name="schedjoules_location_picker_current_location_permission_inform_about_phone_settings">Bitte erteile die Standort Berechtigung in den Systemeinstellungen um diese Funktion später nutzen zu können.</string>
   <string name="schedjoules_location_picker_current_location_error">Dein Standort konnte nicht ermittelt werden. Hier tippen um es erneut zu versuchen.</string>
   <string name="schedjoules_location_picker_caption_place_suggestions">Vorschläge</string>
   <string name="schedjoules_location_picker_caption_recent_locations">Zuletzt gesucht</string>
```

**Comment by wilfredstegeman** [comment]
The German translations differs from the English one. 

Current location > Mein Standort
- In English we don't say 'My location'. Is 'Aktueller/Aktuellen Standort' a good alternative?

Recent locations > Zuletzt gesucht
- In English we don't say 'Last searched'. Is 'Letzte Standorte' a good alternative?

**Comment by dmfs** [comment]
I don't think that it's necessary that all translations are exactly "equal". "Mein Standort" is more personal and sounds better to me than "Aktueller Standort".
Also that's what Google Maps uses when you open the navigation:
![device-2017-03-16-105826](https://cloud.githubusercontent.com/assets/1614987/23990838/9394577e-0a37-11e7-97d8-aeeb347b9fcf.png)

I also considered "Letzte Standorte", but that sounds a bit strange to me. "Standort" is the correct translation for "location" when you refer to your current location (and what everyone else uses) but it's not exactly the same as "location" and also has the meaning of "the place where something stands". Which is why it sounds strange to refer to a place as "Standort" unless you're talking about a specific building or other kind of object (including yourself).

I think "zuletzt gesucht" is a the best title for the "recent locations" sections.

**Comment by wilfredstegeman** [comment]
Ok.

**Comment by dmfs** [comment]
It's interesting that Google Maps uses "Mein Standort" ("My location") in the German (and Russian) translation but "Your location" in the English (and French, Italian and Spanish) translation. Not sure if you can explain that with cultural differences.

**Comment by wilfredstegeman** [comment]
The Germans seem to be the odd one out here, because in Dutch it's also "Your location" / 'Jouw locatie'.

**Comment by lemonboston** [comment]
As Marten requested we will start to add descriptions next to the string resources to make translations, review easier by providing some context.

"Locating..." which is displayed during retrieving location became "Find location...", would this be better as "Finding location..." to indicate the progress?

**Comment by dmfs** [comment]
After seeing it in action I think "We could not determine your location." sounds a bit scary. Why does it say "We"?

How about just "Unable to determine your location"?

**Comment by lemonboston** [comment]
I am also in favor of non-personalizing the error messages, other than maybe say "We are sorry, .." which is nice, but then "something happened" is better imo than "we couldn't do something", it's actually in line with reality more, because we usually don't know exactly what happened, maybe there was simply no connection.
"Unable" suggest for me that it is not possible, doesn't go well with "Retry" I think, so maybe something that refers to one happening, like "Failed to..", "Error during..", or even "Couldn't..".
But I am sure this is a topic in itsellf, how to communicate with the user :)

@wilfredstegeman This is where you can always find the current (master branch) strings by the way, in case you ever want to double check something, suggest change:
https://github.com/schedjoules/android-event-discovery-sdk/blob/master/eventdiscovery-sdk/src/main/res/values/strings.xml
https://github.com/schedjoules/android-event-discovery-sdk/blob/master/eventdiscovery-sdk/src/main/res/values-de/strings.xml
https://github.com/schedjoules/android-event-discovery-sdk/blob/master/eventdiscovery-sdk/src/main/res/values-nl/strings.xml
