### ISSUE TITLE
Crash when selecting a result from the suggestions

### ISSUE THREAD

**Issue by dmfs** [schedjoules/android-event-discovery-sdk#156]
```
03-17 21:09:05.574  6660  6660 E AndroidRuntime: Process: com.schedjoules.eventdiscovery.demo, PID: 6660
03-17 21:09:05.574  6660  6660 E AndroidRuntime: java.lang.IllegalStateException: Adapter is not attached to RecyclerView. Enable sticky headers after setting adapter to RecyclerView.
03-17 21:09:05.574  6660  6660 E AndroidRuntime: 	at eu.davidea.flexibleadapter.helpers.StickyHeaderHelper.attachToRecyclerView(StickyHeaderHelper.java:78)
03-17 21:09:05.574  6660  6660 E AndroidRuntime: 	at eu.davidea.flexibleadapter.FlexibleAdapter$5.run(FlexibleAdapter.java:1395)
03-17 21:09:05.574  6660  6660 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:815)
03-17 21:09:05.574  6660  6660 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:104)
03-17 21:09:05.574  6660  6660 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:207)
03-17 21:09:05.574  6660  6660 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5688)
03-17 21:09:05.574  6660  6660 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-17 21:09:05.574  6660  6660 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
03-17 21:09:05.574  6660  6660 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)
```

**Comment by lemonboston** [comment]
Status:
I couldn't reproduced it at first, but thought from the error message that simply the `FlexibleAdapter` initialization order has to be changed. But after changing that and testing, the crash happened when I rotated the location picker screen and then selected a city. So the real problem is execution order when `EventListFragment` is standing up after both rotation and `onActivityResult`. So I am working on fixing that, some of that also relates to state management in this retained fragment.

**Comment by dmfs** [comment]
So once again the problem is caused by retained fragments? Can't we just get rid of it?

**Comment by lemonboston** [comment]
This bug would have happened with non-retained fragment as well, the problem was that `FlexibleAdapter/RecyclerView` were updated twice when we returned from rotated location picker, once from `onCreateView()` and once from `onActivityResult()` and it caused some problem in `FlexibleAdapter` internals.
So I moved the update to `onResume()` where 3 boolean states are checked now. (It would be 2 with non-retained fragment.). It also allowed some simplification to earlier `PlaceSelection` component: callback is not handled now, so it's similar change as you did with Permissions.
I am going to create the pull request.
