### ISSUE TITLE
GetCityTask failed

### ISSUE THREAD

**Issue by dmfs** [schedjoules/android-event-discovery-sdk#157]
Happens on my Blackview with Android 6 when I tap on "current location". All apps are up to date.

```
03-17 21:18:12.020  7584  7584 E CurrentLocationModule: GetCityTask failed
03-17 21:18:12.020  7584  7584 E CurrentLocationModule: java.io.IOException: Service not Available
03-17 21:18:12.020  7584  7584 E CurrentLocationModule: 	at android.location.Geocoder.getFromLocation(Geocoder.java:136)
03-17 21:18:12.020  7584  7584 E CurrentLocationModule: 	at com.schedjoules.eventdiscovery.framework.location.tasks.GetCityTask.doInBackgroundWithExceptionForNonCached(GetCityTask.java:54)
03-17 21:18:12.020  7584  7584 E CurrentLocationModule: 	at com.schedjoules.eventdiscovery.framework.location.tasks.GetCityTask.doInBackgroundWithExceptionForNonCached(GetCityTask.java:42)
03-17 21:18:12.020  7584  7584 E CurrentLocationModule: 	at com.schedjoules.eventdiscovery.framework.async.CachingSafeAsyncTask.doInBackgroundWithException(CachingSafeAsyncTask.java:63)
03-17 21:18:12.020  7584  7584 E CurrentLocationModule: 	at com.schedjoules.eventdiscovery.framework.async.CachingSafeAsyncTask.doInBackgroundWithException(CachingSafeAsyncTask.java:31)
03-17 21:18:12.020  7584  7584 E CurrentLocationModule: 	at com.schedjoules.eventdiscovery.framework.async.SafeAsyncTask.doInBackground(SafeAsyncTask.java:64)
03-17 21:18:12.020  7584  7584 E CurrentLocationModule: 	at com.schedjoules.eventdiscovery.framework.async.SafeAsyncTask.doInBackground(SafeAsyncTask.java:32)
03-17 21:18:12.020  7584  7584 E CurrentLocationModule: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
03-17 21:18:12.020  7584  7584 E CurrentLocationModule: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-17 21:18:12.020  7584  7584 E CurrentLocationModule: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
03-17 21:18:12.020  7584  7584 E CurrentLocationModule: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
03-17 21:18:12.020  7584  7584 E CurrentLocationModule: 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by lemonboston** [comment]
They say here that rebooting helps:
http://stackoverflow.com/a/16119804/4247460
There are also issued bugs for this exception with GeoCoder:
http://code.google.com/p/android/issues/detail?id=38009
https://issuetracker.google.com/issues/35823462

Note: the error handling story will add a retry button there.

So since it's probably not clear what causes this or how to handle, I suggest that we put this aside until we know that this happens regularly. I think it would be very useful to bring forward the error/crash reporting story:
https://github.com/schedjoules/backlog/issues/112
There could be many specific errors across the Android versions and devices, edge cases we don't think about and we will never know about them failing the users out there. I would be very happy to see a dashboard with all errors, it was very nice with Crashlytics at a previous project (not suggesting that service, just an example).

@dmfs What do you think?

But if we want to fix this now, there is a comment on the 3rd link:
"Anyway just use Google Geocoding API: https://developers.google.com/maps/documentation/geocoding/"
So we can probably switch to that. I don't know whether Google Maps API need a different API key then Places API.
https://developers.google.com/places/web-service/get-api-key

**Comment by dmfs** [comment]
Before switching to the Maps API we have to consider implications for partners. So for now we'll try to monitor and analyse this.

**Comment by lemonboston** [comment]
As said it's worth coming back to it after #139 so that we have Google Maps API access, setting it as 'blocked' now.

**Comment by lemonboston** [comment]
@dmfs What should we do with this one?

As I remember you mentioned it doesn't happen now on your Blackview but as comments mentioned above say it may be that reboot solved it, so it may be a bit unpredictable. It may still happen for users out there. (error reporting?..;))
If we want to solve this with that suggested replacement of GeoCoder with Google Maps API call then I guess we need to check the API key first, whether it needs extra enabling.
I tried this one with ours:
https://maps.googleapis.com/maps/api/geocode/json?address=1600+Amphitheatre+Parkway,+Mountain+View,+CA&key=YOUR_API_KEY
(from https://developers.google.com/maps/documentation/geocoding/)
Got this response:
```json
{
   "error_message" : "This IP, site or mobile application is not authorized to use this API key. Request received from IP address 80.98.84.114, with empty referer",
   "results" : [],
   "status" : "REQUEST_DENIED"
}
```

Note: without the API key parameter it actually returns result, but after resent many times (around 20), it shows this:
```json
{
   "error_message" : "You have exceeded your rate-limit for this API.",
   "results" : [],
   "status" : "OVER_QUERY_LIMIT"
}
```

**Comment by dmfs** [comment]
Let's close this for now and wait for error reporting to see if this is still an issue.
