### ISSUE TITLE
Back arrow button missing from Event Details screen

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#37]

**Comment by dmfs** [comment]
Yes, but before we re-add it we need to define the screen hierarchy. The previous implementation always went back in history, which was wrong. The "Up" button should go back in the screen hierarchy. In particular that means it should go back to the list, even if the details were entered through a different entry point.

**Comment by dmfs** [comment]
So for now I'd rather leave it without "up" arrow.

**Comment by lemonboston** [comment]
I see that the navigation have to be worked out. 
Just my personal note on the UP navigation: I am not sure users are aware of this concept. I know how it is defined by google and how it should be used, but I think users mostly just look at it like a back button. But I haven't done a UX study on this :)

For me the screen looks strange without the arrow. It looks like I am somewhere but can't go back. Not sure I've seen this in other apps.

**Comment by dmfs** [comment]
The major problem with the Up vs. back navigation is that so many apps do it wrong, including pretty much every Google app. I actually like the idea of distinguishing both actions and I want to get it right.
Every user will understand how to get back to the list, so this it no really an issue.

**Comment by lemonboston** [comment]
@dmfs What would be then the required behaviour for the details screen UP arrow that we want to implement at this point?:

Option 1:
It is always shown. If screen was opened from the list, tapping on UP arrow resumes the list (same as back button).
If details screen was opened directly from partner app, the up arrow opens the list screen filtering to last selected location and time of the event just viewed (or today)?

Option 2:
UP arrow is only shown when the details screen is opened from the list view, tapping on it resumes the list (same as back button).

A note on the general topic: getting the navigation and screen hierarchy right with screens that can have multiple entry points doesn't seem to be trivial to me because of issues that come up with the number of instances of the screens and the way the framework handles those related configurations (launchmode or intent flags).
See: https://github.com/dmfs/opentasks/issues/283#issuecomment-252298845
Maybe it could be useful later to have a document listing all the possible user journeys, so we can check implementation against that, and also maybe create automated UI tests to cover them.

**Comment by dmfs** [comment]
I've created a navigation concept, just need to draw it in Fluid UI.

Short answer:
The details screen will always have an UP arrow.

Long answer:
The UP arrow will always take you to the list view. If you enter the details view directly from the partner app (rather than the list view) we'll open an initial discovery screen. If you come from the list view the action is the same as going "back".

Implementation detail:
We'll drop the separate details activity. Instead, I'm planning to have only a single activity that hosts the MicroFragments. The initial MicroFragment is passed as an extra.
If we have to provide an Intent for a component that doesn't know about MicroFragments, we'll add a ProxyActivity that catches the Intent and launches the right MicroFragment.

Navigation will be much easier that way. The feedback WebView will be hosted in another MicroFragment.

Positive side effect: since all the action goes on in a single Activity, we don't need to launch services in advance. Instead we just need to bind them once when the Activity starts. That also makes it trivial to determine when a session starts and ends.

So we won't start working on this before we switched to MicroFragments.

**Comment by lemonboston** [comment]
Thanks, it's great that you started to create the navigation concept in some design tool, looking forward to see!

About the architecture: so we are moving to one Activity approach, sounds exciting, looking forward to that as well, how we can make that work.

(Moving this now issue back in the line.)

**Comment by dmfs** [comment]
This has been resolved with #137
