### ISSUE TITLE
Event detail loader is loading again when going back from details

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#416]
`EventDetailLoaderMicroFragment.LoaderFragment` is resumed unnecessarily when going back from details screen which starts the loading again before being destroyed. It's not noticable on the UI.

Logs:
Opening an event details from the list for the first time:
```
08-17 20:19:41.486 D/Investigator: [main] LoaderFragment{d6077cc #0 id=0x7f0d0009}.onResume()
08-17 20:19:41.498 D/Investigator: [pool-4-thread-1] EventDetailLoaderMicroFragment$LoaderFragment$3@e03f464.execute() | action loading
```
Then pressing back:
```
08-17 20:19:46.895 D/Investigator: [main] LoaderFragment{d6077cc #0 id=0x7f0d0009}.onResume()
08-17 20:19:46.908 D/Investigator: [pool-4-thread-2] EventDetailLoaderMicroFragment$LoaderFragment$3@e6f46de.execute() | action loading
08-17 20:19:47.202 D/Investigator: [main] LoaderFragment{d6077cc #0 id=0x7f0d0009}.onDestroy()
```

**Comment by dmfs** [comment]
oh, yeah, that's because `FragmentManager` still goes through the entire life cycle when you skip fragments when going back. Stupid `FragmentManager`. I think there was something new to avoid that though.

**Comment by lemonboston** [comment]
I wanted to ask this before as well, can't microfragments not add the skipped Fragments to the backstack in the first place? Isn't that information available at that time? So just commiting without adding to backstack. Then there is no need to do anything extra on back transitions.

**Comment by dmfs** [comment]
The problem is that you don't add *Fragments* to the backstack but *Fragment transactions*. If we start a loader fragment and replace the list fragment without adding the transaction to the backstack, the list fragment would not return when we go back, because the FragmentManager would not "undo" the transaction.
What we could try is placing two transactions, the first one just removes the previous fragment and is added to the backstack and the second one adds the loader fragment without adding it to the backstack. Not sure if that would work. I'll give it a try.

**Comment by dmfs** [comment]
Hmm... that might be possible, but
1) it requires an architectural change because at present our Transitions returns exactly one FragmentTransaction
2) there is a chance that these two transitions would not play at the same time. It's quite possible that they are either serialized or that the animation of one of both is cancelled.

**Comment by lemonboston** [comment]
I don't understand the question fully at this point, but I just tried something and just noting it here:
`ForwardTransition` with:
```
        if (!mNextStep.skipOnBack())
        {
            fragmentTransaction.addToBackStack("skip");
        }
```
and using that in `EventDetailLoaderMicroFragment.LoaderFragment` works in the sense that it went back to list screen after pressing back. Although the loader fragment still resumed a 2nd time before being destroyed.

**Comment by dmfs** [comment]
Hmm … I'll give it a try myself.
