### ISSUE TITLE
State transition approach in event list loading component

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#52]
Code complexity could be greatly reduced within current `EventListItemsProviderImpl` with something like the below. There would be a `State` object containing all stateful objects, kept by `EventListItemsProviderImpl`, and there would be specific StateTransitions that would operate on this State.

```
class State {
    EventListBackgroundMessage mBackgroundMessage;
    EventListItems mItems;
    EventListLoadingIndicatorOverlay mLoadingIndicatorOverlay;
    EnumMap<ScrollDirection, ResultPage<Envelope<Event>>> mLastResultPages;
    GeoLocation mLocation;
    Map<ScrollDirection, Boolean> mIsLoading;
    Map<ScrollDirection, Boolean> mIsInErrorMode;
    Map<ScrollDirection, TaskParam> mErrorTaskParam;
}

new LoadingStartedTransition(direction).apply(state);

new AddNewItemsTransition(newItems, resultPage, direction).apply(state);

new ToErrorStateTransition(direction).apply(state);
```

**Comment by dmfs** [comment]
Sorry, I won't approve this. I'm sure we can find better ways to deal with the complexity.
For instance, if I'm not mistaken, `mBackgroundMessage` and `mLoadingIndicatorOverlay` are only used when the list is loading the initial content respectively when an error occurs during that. Is that right? In that case, why do we carry it all the way with us once the initial content has been loaded?
Wouldn't it be better to make these separate fragments and just switch to the one containing the list once the content has been loaded?
Similarily, when a new location or filter is selected or the user jumps to a specific time, we could just replace the current list fragment with a new one having the new parameters (probably showing an intermediate loader fragment). That would already reduce the complexity a lot. We have less state variables to deal with. Also it's easier to deal with filter parameter updates, because we just create a new Fragment and launch it instead of having to update the state or a single complex fragment.
From a callers perspective that would make a fragment sort of immutable. Don't get me wrong, I know that a Fragment couldn't be any further from an immutable object. What I mean by "immutable" in this case is that you can not modify the filter params after the fragment has been created. Instead you create a new one with new params and execute an X-Fade transition.
That also makes it easier to deal with empty results. If a loading step gets an empty response it can launch a "RecommendationFragment" instead of the regular "SearchResultFragment". No need to handle both cases in the same class.
Let's use "Fragment Polymorphism" and create specialized Fragments that adhere to some sort of SRP (in terms of what it presents to the user). So instead of trying to manage a huge state that's getting bigger and more complex with every feature, lets try to reduce the state and create small specialized Fragments (in terms of UI responsibility) that we barely have to touch when we add new features. Ideally we can cover new features by adding a new Fragment instead of modifying an existing one. Easier to maintain, easier to test, easier to understand.
Let's have a quick call if you have any questions or concerns.

**Comment by lemonboston** [comment]
No need for the call, I really like these suggestions myself too, thanks for giving it some thought and sharing it.
