### ISSUE TITLE
In order to get started quickly, as a partner I want a good documentation.

### ISSUE THREAD

**Issue by dmfs** [schedjoules/android-event-discovery-sdk#55]

**Comment by dmfs** [comment]
I've created a 5-minute-install page at https://github.com/schedjoules/android-event-discovery-sdk/wiki/5-minutes-install
@lemonboston please review
I'll also ask our launch partners to review this

**Comment by dmfs** [comment]
Also added a Customization Guide: https://github.com/schedjoules/android-event-discovery-sdk/wiki/Customization-Guide

**Comment by dmfs** [comment]
Just added Proguard and Internet permissions to the 5-minutes-install guide

**Comment by lemonboston** [comment]
I've looked through the documentation and done the integration in a new project, it was straightforward and everything worked.

Some minor notes:

- Maybe we could mention minSdk and targetSdk somewhere
- I suggest switching the order of "Enable data binding" and "Add packagingOptions" because as I was setting up the project I already tried to build at that point and it failed because of the packaging options
- Code snippet for ApiService could contain the import statements as well, I always find that helpful, no need for the client to select 10 classes to import. It may be useful too at the snippets with DateTime and Duration
- Maybe omitting the suggestion here: "This step only applies if you use Proguard to optimize, shrink or obfuscate your apk, something that you really should do."
- These calls needs Activity: `new BasicEventDiscovery().start(context)` `new UidEventDetails(eventUid).show(context)`
