### ISSUE TITLE
In order to improve our visibility we need to improve the current Powered by text

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#63]
@wilfredstegeman commented on [Fri Dec 30 2016](https://github.com/schedjoules/backlog/issues/98)

I suggest to move the current Powered by text to a sticky footer at the bottom:

- background color #000000
- text color #ffffff
- text in CAPITALS
- hyperlink the complete text with an option to change the link as we do with the feedback url

Screenshots

- Mockup SchedJoules
- Example HelpShift

![schedjoules-powered-by-footer](https://cloud.githubusercontent.com/assets/5968782/21562383/dc036ab8-ce78-11e6-8111-eba00805eb15.png)
![helpshift-powered-by](https://cloud.githubusercontent.com/assets/5968782/21562385/e14cf804-ce78-11e6-84ef-433c6025f5be.png)

---

@lemonboston commented on [Fri Dec 30 2016](https://github.com/schedjoules/backlog/issues/98#issuecomment-269790271)

I am not sure if this is agreed already, but I started to work on it.

**Comment by dmfs** [comment]
Not a fan of this. Looks a bit desperate to me.

**Comment by wilfredstegeman** [comment]
Can you elaborate on 'desparate'? As said before, we have to mention ourselves in partner apps, it's the best exposure and marketing of ourselves we can get. Moving the current text to the bottom and center is also an option, but that doesn't seem feasible. I'm open for other options, but the way it's currently shown has to change at least. 


		_____________________________

**Comment by lemonboston** [comment]
@dmfs , @wilfredstegeman please check the apk in Slack with the black bottom bar, I put this on hold until solution is discussed.

**Comment by dmfs** [comment]
I mean that it looks as if we badly need some attention. We should show enough self-confidence to not rub it in the users' faces all the time where this is coming from.

Our use case can not be compared to the Helpshift use case. As a regular user you only see the Helpshift screen when you need some support, i.e. something is wrong, doesn't work as expected or any other problem occurred. So the goal of an app developer should be that actually no user ever needs to see that Helpshift screen.
That being said, even in their use case I would refrain from that ugly bar.

In our case, the goal is that the user returns as often as possible. That's a fundamental difference. The black bar on the bottom almost reminds me on the typical ad banners. It looks desperate and cheap and I think that many users feel the same (especially since it's pretty uncommon on Android).

Why don't we take the good old "about" menu option approach? We just added a menu for the "feedback" option. We could just as well add an "about" entry. This has several advantages:

* it's way less likely clicked by accident
* in an about screen we can use proper branding (i.e. use the actual logo)
* we can add some important info right to the about screen (so you don't have to look it up on the website landing page)
* no waste of precious space
* no ugly bottom bar

A simple implementation would just link to the about web page and open it in a webview.

The second place to put a "powered by SchedJoules" would be an intro (just like the "powered by Android" when you boot an Android device).

**Comment by dmfs** [comment]
Another option that I would prefer over the black bar:
Whenever we load any content and show a loading indicator we could add a text like, "SchedJoules is loading your results"

**Comment by rutgerg** [comment]
Let's go for the black bar for now. It is common, effective and solves the Google issue

**Comment by dmfs** [comment]
This is not related to the Google issue. And "common" is at least debatable.

**Comment by rutgerg** [comment]
Not a matter of good or bad. Matter of making a decision, implement and revisit later.
